FROM python:3.13-slim

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT="/opt/venv"

ENV PATH="/opt/venv/bin:$PATH"

ENV UV_LINK_MODE=copy

COPY pyproject.toml uv.lock ./

RUN pip install --no-cache-dir uv

RUN uv sync --frozen --no-install-project

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]